/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package records;

import capture.ControlPerson;
import capture.ModelPerson;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import main.Settings;
import utility.DataBase;

/**
 *
 * @author Souflexy
 */
public class ModifyData extends javax.swing.JDialog {
int id,selectedRow;
Data d=new Data();
String photoPath=Settings.photo.getAbsolutePath();
    ControlPerson cod = new ControlPerson();
    DataBase db=new DataBase();
    public ModifyData(java.awt.Frame parent, boolean modal,int id,int selectedRow) {
        super(parent, modal);
        initComponents();
        this.selectedRow=selectedRow;
        saveBtn1.setVisible(false);
        undoBtn.setVisible(false);
        txt_name.setEditable(false);
        txt_lastname.setEditable(false);
        txt_birth.setEditable(false);
        txt_major.setEnabled(false);
        txt_year.setEnabled(false);
        txt_place.setEditable(false);
        txt_phone_number.setEditable(false);
        txt_lang.setEnabled(false);
        AddImage(id);
        FillInfo(id);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        txt_place = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        txt_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_id_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        txt_major = new javax.swing.JComboBox<>();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        txt_year = new javax.swing.JComboBox<>();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        txt_birth = new javax.swing.JFormattedTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_lang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        txt_phone_number = new javax.swing.JTextField();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        txt_lastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prevBtn = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        photo_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveBtn1 = new keeptoo.KButton();
        nextBtn = new keeptoo.KButton();
        jLabel15 = new javax.swing.JLabel();
        label_register = new javax.swing.JLabel();
        undoBtn = new keeptoo.KButton();
        EditBtn = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(90, 68, 193));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 255));
        jLabel14.setText("Student ID:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, 30));

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel3.setkFillBackground(false);
        kGradientPanel3.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_place.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_place.setBorder(null);
        txt_place.setOpaque(false);
        txt_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placeActionPerformed(evt);
            }
        });
        kGradientPanel3.add(txt_place, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 30));

        getContentPane().add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Birthdate");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        kGradientPanel7.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel7.setkFillBackground(false);
        kGradientPanel7.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_name.setBorder(null);
        txt_name.setOpaque(false);
        kGradientPanel7.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        getContentPane().add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Language");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        txt_id_label.setBackground(new java.awt.Color(132, 242, 145));
        txt_id_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id_label.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        kGradientPanel6.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel6.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel6.setkFillBackground(false);
        kGradientPanel6.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_major.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_major.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Computer Science", "Biology", "Maths", "Statistics", "Geology" }));
        txt_major.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel6.add(txt_major, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        getContentPane().add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, 30));

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_year.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "First year (1st)", "Second year (2nd)", "Third year (3rd)", "Master 1 (M1)", "Master 2 (M2)", "Doctorat (PHD)" }));
        txt_year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yearActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 160, 30));

        kGradientPanel4.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel4.setkFillBackground(false);
        kGradientPanel4.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_birth.setBorder(null);
        try {
            txt_birth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_birth.setToolTipText("ex:01/01/2021");
        txt_birth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_birth.setOpaque(false);
        txt_birth.setPreferredSize(new java.awt.Dimension(76, 16));
        kGradientPanel4.add(txt_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        getContentPane().add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 140, 30));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_lang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Francais", "English" }));
        txt_lang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_langActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txt_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Place of birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        kGradientPanel5.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel5.setkFillBackground(false);
        kGradientPanel5.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_phone_number.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_phone_number.setBorder(null);
        txt_phone_number.setOpaque(false);
        kGradientPanel5.add(txt_phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 130, 30));

        kGradientPanel8.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel8.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel8.setkFillBackground(false);
        kGradientPanel8.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_lastname.setBorder(null);
        txt_lastname.setOpaque(false);
        kGradientPanel8.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        getContentPane().add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Major");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setText("First Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        prevBtn.setText("Prev");
        prevBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prevBtn.setkAllowTab(false);
        prevBtn.setkEndColor(new java.awt.Color(153, 153, 255));
        prevBtn.setkHoverEndColor(new java.awt.Color(22, 92, 22));
        prevBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        prevBtn.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        prevBtn.setkPressedColor(new java.awt.Color(28, 72, 28));
        prevBtn.setkStartColor(new java.awt.Color(102, 102, 255));
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });
        getContentPane().add(prevBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 80, 30));
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Phone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));
        getContentPane().add(photo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 190));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("Edit Data");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Filled_Circle_15px_1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        saveBtn1.setText("Save");
        saveBtn1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        saveBtn1.setkAllowTab(false);
        saveBtn1.setkEndColor(new java.awt.Color(153, 153, 255));
        saveBtn1.setkHoverEndColor(new java.awt.Color(22, 92, 22));
        saveBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        saveBtn1.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        saveBtn1.setkPressedColor(new java.awt.Color(28, 72, 28));
        saveBtn1.setkStartColor(new java.awt.Color(102, 102, 255));
        saveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 80, 30));
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nextBtn.setText("Next");
        nextBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nextBtn.setkAllowTab(false);
        nextBtn.setkEndColor(new java.awt.Color(153, 153, 255));
        nextBtn.setkHoverEndColor(new java.awt.Color(22, 92, 22));
        nextBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        nextBtn.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        nextBtn.setkPressedColor(new java.awt.Color(28, 72, 28));
        nextBtn.setkStartColor(new java.awt.Color(102, 102, 255));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 80, 30));
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setBackground(new java.awt.Color(90, 68, 193));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("Registery Date:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, 30));

        label_register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_register.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 130, 30));

        undoBtn.setText("Undo");
        undoBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        undoBtn.setkAllowTab(false);
        undoBtn.setkEndColor(new java.awt.Color(153, 153, 255));
        undoBtn.setkHoverEndColor(new java.awt.Color(22, 92, 22));
        undoBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        undoBtn.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        undoBtn.setkPressedColor(new java.awt.Color(28, 72, 28));
        undoBtn.setkStartColor(new java.awt.Color(102, 102, 255));
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(undoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 80, 30));
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        EditBtn.setText("Edit");
        EditBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        EditBtn.setkAllowTab(false);
        EditBtn.setkEndColor(new java.awt.Color(153, 153, 255));
        EditBtn.setkHoverEndColor(new java.awt.Color(22, 92, 22));
        EditBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditBtn.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        EditBtn.setkPressedColor(new java.awt.Color(28, 72, 28));
        EditBtn.setkStartColor(new java.awt.Color(102, 102, 255));
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 80, 30));
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        setSize(new java.awt.Dimension(1002, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placeActionPerformed

    private void txt_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yearActionPerformed

    private void txt_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_langActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_langActionPerformed

    
    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
       
        if(this.selectedRow==0)
         {}
         else{
             selectedRow--; 
     FillInfo(Integer.valueOf(d.tabela.getValueAt(selectedRow,1).toString()));
     AddImage(Integer.valueOf(d.tabela.getValueAt(selectedRow,1).toString()));
         }
    }//GEN-LAST:event_prevBtnActionPerformed

    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
         DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
         saveBtn1.setVisible(false);
         EditBtn.setVisible(true);
         prevBtn.setVisible(true);
         nextBtn.setVisible(true);
         undoBtn.setVisible(false);
        try {

            df.setLenient(false);
            df.parse(txt_birth.getText());

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Invalid Date entered!");
            return ;
        }
        try {
             if (txt_name.getText().equals("") || txt_name.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Fill all the fields");
        } else if (txt_lastname.getText().equals("") || txt_lastname.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Fill all the fields");
        } else if (txt_birth.getText().equals("") || txt_birth.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Fill al the fields");
        } 
        else if (txt_phone_number.getText().equals("  -   -   ") || txt_phone_number.getText().equals("  -   -    ")) {
            JOptionPane.showMessageDialog(null, "Fill al the fields");
        } else if (txt_place.getText().equals("") || txt_place.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Fill al the fields");
        } else if (txt_major.getSelectedItem().equals("-Select-")) {
            JOptionPane.showMessageDialog(null, "Fill all the fields");
        } else if (txt_year.getSelectedItem().equals("-Select-")) {
            JOptionPane.showMessageDialog(null, "Fill all the fields");
        } else if (txt_lang.getSelectedItem().equals("-Select-")) {
            JOptionPane.showMessageDialog(null, "Fill al the fields");}
            else if((new SimpleDateFormat("dd/MM/yyyy").parse(txt_birth.getText()).compareTo(new Date()))>0)
            {
                JOptionPane.showMessageDialog(null, "Invalid Date entered!");

            }

            else{
                int res=JOptionPane.showConfirmDialog(null,"Are you sure you want to save the changes ?");
                if(res!=0)
                    return;
                else{
                ModelPerson mod = new ModelPerson();
                mod.setId(id);
                mod.setFirst_name(txt_name.getText());
                mod.setLast_name(txt_lastname.getText());
                mod.setPhone(txt_phone_number.getText());
                mod.setMajor((String) txt_major.getSelectedItem());

                mod.setBirthdate(txt_birth.getText());
                mod.setPlace(txt_place.getText());
                mod.setYear((String) txt_year.getSelectedItem());
                mod.setLanguage((String) txt_lang.getSelectedItem());
                cod.update(mod, id);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveBtn1ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
     
        if(this.selectedRow==d.tabela.getRowCount()-1)
      {}
      else{
             selectedRow++;
      FillInfo(Integer.valueOf(d.tabela.getValueAt(selectedRow,1).toString()));
     AddImage(Integer.valueOf(d.tabela.getValueAt(selectedRow,1).toString()));
    }//GEN-LAST:event_nextBtnActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
             FillInfo(Integer.valueOf(txt_id_label.getText()));
             saveBtn1.setVisible(false);
             undoBtn.setVisible(false);
             txt_name.setEditable(false);
             txt_lastname.setEditable(false);
             txt_birth.setEditable(false);
             txt_major.setEnabled(false);
             txt_year.setEnabled(false);
             txt_place.setEditable(false);
             txt_phone_number.setEditable(false);
             txt_lang.setEnabled(false);
             EditBtn.setVisible(true);
             prevBtn.setVisible(true);
             nextBtn.setVisible(true);
    }//GEN-LAST:event_undoBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        saveBtn1.setVisible(true);
        undoBtn.setVisible(true);
        txt_name.setEditable(true);
        txt_lastname.setEditable(true);
        txt_birth.setEditable(true);
        txt_major.setEnabled(true);
        txt_year.setEnabled(true);
        txt_place.setEditable(true);
        txt_phone_number.setEditable(true);
        txt_lang.setEnabled(true);
        prevBtn.setVisible(false);
        nextBtn.setVisible(false);
        EditBtn.setVisible(false);
    }//GEN-LAST:event_EditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyData dialog = new ModifyData(new javax.swing.JFrame(), true,-1,-1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void AddImage(int id)
    {
        try{
                String imageFile = photoPath + "\\person." + id + ".1.jpg"; 
                File img=new File(imageFile);
                ImageIcon photo=new ImageIcon(ImageIO.read(img));
                photo_label.setIcon(photo);
              }
              catch(Exception e)
              {
                  System.out.println("No Picture Found");
                  photo_label.setIcon(null);
              }
        
    }
    private void FillInfo(int id)
    {
        
          db.connect();
         db.runSQL("SELECT * FROM person WHERE id = " +id);
        
         try{
         db.rs.first();
            txt_id_label.setText(id+"");
            txt_lastname.setText(db.rs.getString("last_name"));
            txt_name.setText(db.rs.getString("first_name"));
            txt_phone_number.setText(db.rs.getString("phone"));
            txt_place.setText(db.rs.getString("place"));
            txt_lang.setSelectedItem(db.rs.getString("language"));
            txt_major.setSelectedItem(db.rs.getString("major"));
            txt_year.setSelectedItem(db.rs.getString("year"));
            txt_birth.setText(db.rs.getString("birthdate"));
            label_register.setText(db.rs.getString("register_date"));
            
         
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
         db.disconnect();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton EditBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private javax.swing.JLabel label_register;
    private keeptoo.KButton nextBtn;
    private javax.swing.JLabel photo_label;
    private keeptoo.KButton prevBtn;
    private keeptoo.KButton saveBtn1;
    private javax.swing.JFormattedTextField txt_birth;
    private javax.swing.JLabel txt_id_label;
    private javax.swing.JComboBox<String> txt_lang;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JComboBox<String> txt_major;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone_number;
    private javax.swing.JTextField txt_place;
    private javax.swing.JComboBox<String> txt_year;
    private keeptoo.KButton undoBtn;
    // End of variables declaration//GEN-END:variables
}
